# -*- coding: utf-8 -*-
"""AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JQdiKFN3hTQuUaWSP5wnmPhjF-q3rGH
"""

from google.colab import files
uploaded = files.upload()  # سيتيح لك رفع الملف من جهازك المحلي

import zipfile

# استخراج الملف المضغوط
with zipfile.ZipFile('AI.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/AI')  # هذا سيقوم بفك الضغط في مجلد '/content/AI'

import os

# عرض محتويات المجلد الذي يحتوي على النموذج
print(os.listdir('/content/AI'))

model_path = '/content/AI/AI/model.savedmodel'  # تأكد من أن المسار صحيح
model = tf.saved_model.load(model_path)

import tensorflow as tf

# المسار الذي يحتوي على النموذج
model_path = '/content/AI/AI/model.savedmodel'

# حاول تحميل النموذج مرة أخرى
try:
    model = tf.saved_model.load(model_path)
    print("تم تحميل النموذج بنجاح!")
except Exception as e:
    print(f"حدث خطأ أثناء تحميل النموذج: {str(e)}")

options = tf.saved_model.LoadOptions(experimental_io_device='/job:localhost')
model = tf.saved_model.load(model_path, options=options)

# استبدال صورة معينة للاختبار
img_path = '/content/AI/AI/glasses.jpeg'  # قم بتغيير المسار إلى الصورة التي ترغب في اختبارها
img = tf.io.read_file(img_path)
img = tf.image.decode_jpeg(img, channels=3)
img = tf.image.resize(img, (224, 224))  # تغيير الحجم إذا لزم الأمر
img_array = tf.expand_dims(img, 0)  # إضافة بعد إضافي للصورة

# احصل على التنبؤات من النموذج
predictions = model(img_array)

# عرض التنبؤات
print(predictions)

# إذا كانت التنبؤات على شكل Tensor
predictions = predictions.numpy()

# العثور على الفئة الأكثر احتمالاً
predicted_class = np.argmax(predictions, axis=1)
print(f"الفئة المتنبأ بها: {predicted_class}")